version: "3.8"

services:
  app:
    hostname: app
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - .:/app
      - appdeps:/app/node_modules:cached
    working_dir: /app
    tty: true

volumes:
  appdeps:
